apiVersion: v1
kind: Service
metadata:
  name: my-app-active
  namespace: default
spec:
  selector:
    app: my-app
    rollout.argoproj.io/pod-template-hash: "blue"  # Label to select the "blue" pods (current stable version)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-preview
  namespace: default
spec:
  selector:
    app: my-app
    rollout.argoproj.io/pod-template-hash: "green"  # Label to select the "green" pods (new version)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
